# Generated by Django 5.1 on 2024-08-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_area_location_alter_area_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='type',
            field=models.CharField(choices=[('UK_REGION', 'UK Region'), ('GRID_CONSTRAINT_ZONE', 'Grid Constraint Zone'), ('LOCAL_AUTHORITY', 'Local Authority'), ('GRID_SUPPLY_POINT', 'Grid Supply Point'), ('PRIMARY_SUBSTATION', 'Primary Substation'), ('SECONDARY_SUBSTATION', 'Secondary Substation'), ('LV_FEEDER', 'LV Feeder'), ('POSTCODE_SECTOR', 'Postcode Sector'), ('UPRN', 'UPRN')], db_index=True, max_length=50),
        ),
    ]
