# Generated by Django 5.1 on 2024-08-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_alter_area_name_alter_area_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'SECONDARY_SUBSTATION')), fields=('name', 'type', 'location'), name='unique_secondary_substation_name_type_location'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'LV_FEEDER')), fields=('name', 'type'), name='unique_lv_feeder_name_type'),
        ),
    ]
