# Generated by Django 5.1 on 2024-09-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_area_unique_secondary_substation_name_type_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='area',
            name='type',
            field=models.CharField(choices=[('UK_REGION', 'UK Region'), ('GRID_CONSTRAINT_ZONE', 'Grid Constraint Zone'), ('LOCAL_AUTHORITY', 'Local Authority'), ('GRID_SUPPLY_POINT', 'Grid Supply Point'), ('PRIMARY_SUBSTATION', 'Primary Substation'), ('SECONDARY_SUBSTATION', 'Secondary Substation'), ('LV_FEEDER', 'LV Feeder'), ('POSTCODE_SECTOR', 'Postcode Sector'), ('POSTCODE', 'Postcode'), ('UPRN', 'UPRN')], db_index=True, max_length=50),
        ),
    ]
