# Generated by Django 5.1 on 2024-09-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0005_alter_area_id_alter_area_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='type',
            field=models.CharField(choices=[('UK_REGION', 'UK Region'), ('GRID_CONSTRAINT_ZONE', 'Grid Constraint Zone'), ('DNO', 'DNO'), ('LOCAL_AUTHORITY', 'Local Authority'), ('GRID_SUPPLY_POINT', 'Grid Supply Point'), ('PRIMARY_SUBSTATION', 'Primary Substation'), ('SECONDARY_SUBSTATION', 'Secondary Substation'), ('LV_FEEDER', 'LV Feeder'), ('POSTCODE_SECTOR', 'Postcode Sector'), ('POSTCODE', 'Postcode'), ('UPRN', 'UPRN')], db_index=True, max_length=50),
        ),
    ]
