# Generated by Django 5.1 on 2024-08-29 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("areas", "0004_area_unique_secondary_substation_name_type_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "current_energy_rating",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "potential_energy_rating",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                        ],
                        max_length=1,
                    ),
                ),
                ("current_environmental_impact_tco2e", models.FloatField()),
                ("potential_environmental_impact_tco2e", models.FloatField()),
                ("floor_area_sqm", models.FloatField()),
                ("yearly_primary_energy_use_kwh_sqm", models.FloatField()),
                (
                    "uprn",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="areas.area"
                    ),
                ),
            ],
        ),
    ]
