# Generated by Django 5.1 on 2024-08-29 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("areas", "0003_alter_area_name_alter_area_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kwh", models.FloatField()),
                (
                    "spatial_resolution",
                    models.CharField(
                        choices=[
                            ("UK_REGION", "UK Region"),
                            ("GRID_CONSTRAINT_ZONE", "Grid Constraint Zone"),
                            ("LOCAL_AUTHORITY", "Local Authority"),
                            ("GRID_SUPPLY_POINT", "Grid Supply Point"),
                            ("PRIMARY_SUBSTATION", "Primary Substation"),
                            ("SECONDARY_SUBSTATION", "Secondary Substation"),
                            ("LV_FEEDER", "LV Feeder"),
                            ("POSTCODE_SECTOR", "Postcode Sector"),
                            ("UPRN", "UPRN"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "temporal_resolution",
                    models.CharField(
                        choices=[
                            ("30M", "Half Hourly"),
                            ("1H", "Hourly"),
                            ("1D", "Daily"),
                        ],
                        db_index=True,
                        max_length=3,
                    ),
                ),
                ("start_timestamp", models.DateTimeField(db_index=True)),
                ("end_timestamp", models.DateTimeField(db_index=True)),
                ("number_of_meters", models.IntegerField()),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="areas.area"
                    ),
                ),
            ],
        ),
    ]
