# Generated by Django 5.1 on 2024-08-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumption',
            options={'verbose_name_plural': 'consumption'},
        ),
    ]
