# Generated by Django 5.1 on 2024-09-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0002_alter_consumption_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='spatial_resolution',
            field=models.CharField(choices=[('UK_REGION', 'UK Region'), ('GRID_CONSTRAINT_ZONE', 'Grid Constraint Zone'), ('LOCAL_AUTHORITY', 'Local Authority'), ('GRID_SUPPLY_POINT', 'Grid Supply Point'), ('PRIMARY_SUBSTATION', 'Primary Substation'), ('SECONDARY_SUBSTATION', 'Secondary Substation'), ('LV_FEEDER', 'LV Feeder'), ('POSTCODE_SECTOR', 'Postcode Sector'), ('POSTCODE', 'Postcode'), ('UPRN', 'UPRN')], db_index=True, max_length=50),
        ),
    ]
